### ISSUE TITLE
Randomly lost control of sensors - Potential anticheat conflict?

### ISSUE THREAD

**Issue by jeffpete** [Rem0o/FanControl.Releases#1821]
Hi,
I recently found out that two of my fans are no longer controllable via FanControl, returning the message that they had been overriden by an external source - nothing has been changed about the system. Currently using a Gigabyte Aorus Pro AC I have tried the following solutions without success:

- Force apply. 
- I have tried different combinations of settings in the bios including setting the offending sensors to be either PWM or voltage and manual control rather than "normal". 
- Turned the pc completely off including power just to see if it was a motherboard issue
- Attempted to change the target curve to see if it was a sensor issue (I changed this to an SSD temperature sensor from HWINFO).
- Updated to the newest version of FanControl
- Updated AMD Chipset Drivers

Other useful information:

- Other programs running which _could_ conflict include: MSI Afterburner (with fan control turned off, and to extent RTSS), HWINFO64, (perhaps) MSI dragon center (although I have set this to not turn on at boot but some of its services still run in the background such as lighting; almost certain it doesn't have a fan control mode).
- Currently using the HWINFO plugin.

One of the sensors can now be controlled again by setting it to manual and PWM; however one of my other fans cannot (it is on a pump header if this helps). Hopefully this isn't a hardware issue. Any help is greatly appreciated!

**EDIT**: So i retried Gigabyte's software and it can control the offending fan. Interestingly enough after uninstalling it, restarting FanControl and refreshing I, for a moment, regained control of both and then lost it again, refreshing seems to shuffle which one I can control. Restarting the PC brings the behaviour back.

**EDIT 2**: I seem to have regained control of the fans again, I will close this issue if I do not encounter this again - however it seems odd to have happened.

**Comment by jeffpete** [comment]
(I think) I have made a development in narrowing down what caused this, I believe that an anticheat, FACEIT, in this case may have been causing this issue. This anticheat has been known to block drivers that it deems are security risks - maybe it had been affecting FanControl(?). As soon as it was uninstalled from my system I no longer had the same issue that I did before and now my two fans that were not working control their headers just fine.
From reading online the normal response from their team is either they push an update that allows compatibility (like in the case of it blocking MSI afterburner, other system monitoring apps and, most interestingly, **Lenovo's Legion fan control**; I don't understand how programs such as FanControl and Lenovo's work under the hood so it could just be pure speculation but it does seem _awfully_ coincidental, expecially given the number of other apps blocked that interface with sensors). The other possibility is that they will ask the dev to "use different drivers".

**Comment by JannesSP** [comment]
I have a similar issue.
After installing the faceit anticheat software and restarting the system, I was no longer able to run the FanControl software at all.
A friend of mine also had the issue. FanControl did not start anymore and all fans were running on 100%.
Is it somehow possible to fix this?
Best, Jannes

**Comment by Menayd** [comment]
Did someone end up finding a solution to this? I'm still facing this issue with Faceit AC. Strangely enough, on some fan headers.

**Comment by rugabunda** [comment]
Any chance this was fixed with fancontrols depreciation of the ring0 driver and release of the PawnIO? Anticheat often acts like an antivirus to prevent tampering which Ring0 was prone to.

**Comment by Rem0o** [comment]
@rugabunda  most likely, in any case the time this issue was raised makes it no longer relevant with the state of the software.  If such issue still persists, better to open a new case.
