### ISSUE TITLE
Fans go to 100% when starting application, switching configuration files, and waking the computer up from sleep.

### ISSUE THREAD

**Issue by mastrauckas** [Rem0o/FanControl.Releases#698]
It appears when I have a graph curve with a high `SelectedResponseTime` setting, the fans rev up to 100% when starting the application, switching configuration files, and waking the computer up from sleep.

A response time over 6 seconds seems to start the issue.  However, it's really noticeable when the setting is at 10 seconds.

Thanks,
Michael

**Comment by McsGone** [comment]
Same here, the latest update doesn't recognize my fan curves at startup for around 30-60 seconds (which makes the fans work at 100%) after which they get "recognized" and start working properly.

**Comment by helljol** [comment]
Hi all, Same for me with v111 my CPU AIO fan goes to 100% after waking up the computer from sleep, curve % value is  Value is NaN a first. Then everything goes back to usual behavior once the CPU curve is displaying a %.
I'm not sure which version i was before upgrading to v111.

Thanks for the great Application anyway !

**Comment by Rem0o** [comment]
@McsGone Increase your startup delay. 

@everyone Also update to V112. I've fixed a state where some fan curves could have 1 "NaN" cycle at startup, triggering 100%.

**Comment by helljol** [comment]
> tate where some fan curves could have 1 "NaN" cycle at startup, triggering 100%.

v112 fix the issue for me Thanks 👍

**Comment by Arundidoo** [comment]
I'm running v112 and I am still experiencing this issue. Upon waking from sleep, and opening fancontrol, no cards will show under the controls, speeds or curves headings. After about 10-20s, the cards will show and the fans will become controlled again.

**Comment by Y4m4k** [comment]
I have the same issue from one of my fan curves too.

**Comment by Rem0o** [comment]
It is normal that there is a delay after waking from sleep for stuff to be controllable again. That's expected. Make sure your default bios fan setup is a tolerable speed before FanControl takes over.

**Comment by Arundidoo** [comment]
> It is normal that there is a delay after waking from sleep for stuff to be controllable again. That's expected. Make sure your default bios fan setup is a tolerable speed before FanControl takes over.

Thank you for the reply, it seemed like there was some issue with my bios not controlling the fan that was running at 100%. A bios update didn't fix it, but for whatever reason the fan became controllable after the bios did memory training for my ram OC.
